packaging_format = 2

id = "ntfy"
name = "ntfy"
description.en = "Send notifications to a smartphone or computer via scripts"
description.fr = "Service pour envoyer des notifications vers un smartphone ou ordinateur via des scripts"

version = "2.26.0~ynh1"

maintainers = ["Alexander Wühr"]

[upstream]
license = "GPL-2.0-only"
website = "https://ntfy.sh/"
demo = "https://ntfy.sh/app"
admindoc = "https://docs.ntfy.sh/"
userdoc = "https://docs.ntfy.sh/"
code = "https://github.com/binwiederhier/ntfy"
fund = "https://liberapay.com/ntfy"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.admin]
	type = "user"

	[install.password]
	type = "password"

[resources]
	[resources.sources]

	[resources.sources.main]
	amd64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.0/ntfy_2.26.0_linux_amd64.tar.gz"
	amd64.sha256 = "0a1c4ed14e96e4e4ae8773151ff032d276932f8f193cf37c7a3d82b0ab595673"

	arm64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.0/ntfy_2.26.0_linux_arm64.tar.gz"
	arm64.sha256 = "3f5b62454eddd5d992641b711fc56c4244564daa0c9dfbbcb0d2db0792b74d19"

	armhf.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.0/ntfy_2.26.0_linux_armv7.tar.gz"
	armhf.sha256 = "918cd74ebdc279a9d4df51a9e7ece89ef01d2dafc9aec9667590327d15e6bcb7"

	autoupdate.strategy = "latest_github_release"
	autoupdate.asset.amd64 = '.*_linux_amd64\.tar\.gz'
	autoupdate.asset.arm64 = '.*_linux_arm64\.tar\.gz'
	autoupdate.asset.armhf = '.*_linux_armv7\.tar\.gz'

	[resources.system_user]

	[resources.install_dir]

	[resources.permissions]
	main.url = "/"
	main.auth_header = false
	main.protected = true
	main.allowed = "visitors"

	[resources.ports]
	main.default = 8080
