packaging_format = 2

id = "ntfy"
name = "ntfy"
description.en = "Send notifications to a smartphone or computer via scripts"
description.fr = "Service pour envoyer des notifications vers un smartphone ou ordinateur via des scripts"

version = "2.23.0~ynh1"

maintainers = ["Alexander Wühr"]

[upstream]
license = "GPL-2.0-only"
website = "https://ntfy.sh/"
demo = "https://ntfy.sh/app"
admindoc = "https://docs.ntfy.sh/"
userdoc = "https://docs.ntfy.sh/"
code = "https://github.com/binwiederhier/ntfy"
fund = "https://liberapay.com/ntfy"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.admin]
	type = "user"

	[install.password]
	type = "password"

[resources]
	[resources.sources]

	[resources.sources.main]
	amd64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.23.0/ntfy_2.23.0_linux_amd64.tar.gz"
	amd64.sha256 = "6a5fdaf7f2b99ec65349c8fe2e38852217a7c08f7d1ba758f77129843f6350ed"

	arm64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.23.0/ntfy_2.23.0_linux_arm64.tar.gz"
	arm64.sha256 = "e62b97cdefc6f0475ef004258cf142a2ff66b1ed79733cfdea606378e3f53efc"

	armhf.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.23.0/ntfy_2.23.0_linux_armv7.tar.gz"
	armhf.sha256 = "4e565412b47f3529bd94a860c654dfc89e344b0d37edd9fa1ab56c275fe84c15"

	autoupdate.strategy = "latest_github_release"
	autoupdate.asset.amd64 = '.*_linux_amd64\.tar\.gz'
	autoupdate.asset.arm64 = '.*_linux_arm64\.tar\.gz'
	autoupdate.asset.armhf = '.*_linux_armv7\.tar\.gz'

	[resources.system_user]

	[resources.install_dir]

	[resources.permissions]
	main.url = "/"
	main.auth_header = false
	main.protected = true
	main.allowed = "visitors"

	[resources.ports]
	main.default = 8080
