packaging_format = 2

id = "ntfy"
name = "ntfy"
description.en = "Send notifications to a smartphone or computer via scripts"
description.fr = "Service pour envoyer des notifications vers un smartphone ou ordinateur via des scripts"

version = "2.26.3~ynh1"

maintainers = ["Alexander Wühr"]

[upstream]
license = "GPL-2.0-only"
website = "https://ntfy.sh/"
demo = "https://ntfy.sh/app"
admindoc = "https://docs.ntfy.sh/"
userdoc = "https://docs.ntfy.sh/"
code = "https://github.com/binwiederhier/ntfy"
fund = "https://liberapay.com/ntfy"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.admin]
	type = "user"

	[install.password]
	type = "password"

[resources]
	[resources.sources]

	[resources.sources.main]
	amd64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.3/ntfy_2.26.3_linux_amd64.tar.gz"
	amd64.sha256 = "56459cc96110d27f1d952351b7ea2883b894a122ca4cc2339c841003c61c138b"

	arm64.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.3/ntfy_2.26.3_linux_arm64.tar.gz"
	arm64.sha256 = "3dbbf626f1c4f2b647509baa109f8330466dc508aa55545f9b58ea5490eb358d"

	armhf.url = "https://github.com/binwiederhier/ntfy/releases/download/v2.26.3/ntfy_2.26.3_linux_armv7.tar.gz"
	armhf.sha256 = "378d188407dde74b3cd9c6a2e226f162811d33ecc92d8fe1433296090032fc59"

	autoupdate.strategy = "latest_github_release"
	autoupdate.asset.amd64 = '.*_linux_amd64\.tar\.gz'
	autoupdate.asset.arm64 = '.*_linux_arm64\.tar\.gz'
	autoupdate.asset.armhf = '.*_linux_armv7\.tar\.gz'

	[resources.system_user]

	[resources.install_dir]

	[resources.permissions]
	main.url = "/"
	main.auth_header = false
	main.protected = true
	main.allowed = "visitors"

	[resources.ports]
	main.default = 8080
