test_format = 1.0

# ntfy needs to be publicly exposed to properly work, see #34 
exclude = "install.private"

[default]
test_upgrade_from.727dfd9.name = "Upgrade from 2.6.2~ynh1"
test_upgrade_from.e89c0fb.name = "Upgrade from 2.5.0~ynh1"
#test_upgrade_from.5b729db.name = "Upgrade from 2.4.0~ynh1"
