test_format = 1.0

[default]
    test_upgrade_from.5b729db.name = "Upgrade from 2.4.0~ynh1"
    test_upgrade_from.ef0ecfc.name = "Upgrade from 2.3.1~ynh1"
    test_upgrade_from.2f539cd.name = "Upgrade from 2.2.0~ynh1"
