test_format = 1.0

[default]

# ntfy needs to be publicly exposed to properly work, see #34
exclude = ["install.private"]

# -------------------------------
# Commits to test upgrade from
# -------------------------------

test_upgrade_from.8b51bf5.name = "Upgrade from 2.11.0~ynh2 "
