test_format = 1.0

[default]

# ntfy needs to be publicly exposed to properly work, see #34
exclude = ["install.private"]

# -------------------------------
# Commits to test upgrade from
# -------------------------------

test_upgrade_from.04bb5b6.name = "Upgrade from 2.11.0~ynh1 "
