#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_backup -s "$install_dir"
ynh_backup -s "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup -s "/etc/systemd/system/$app.service"

ynh_print_info -m "Backup script completed. (YunoHost will then actually copy those files to the archive)"