#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/data"

chmod -R 750 "$install_dir/data"
chown -R "$app:$app" "$install_dir"

ynh_safe_rm "$install_dir/client"
ynh_safe_rm "$install_dir/server"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding configuration file..."

ynh_config_add --template="server.yml" --destination="$install_dir/server.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Open Source Push Notification Server" --log="/var/log/$app/$app.log"

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="limiting requests, excess:.* by zone.*client: <HOST>"

# Allow required basic auth
ynh_app_setting_set --key=auth-header --value=basic-with-password
ynh_app_setting_set --key=protect_against_basic_auth_spoofing --value=False

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add -t "ntfy.sh" -d "$install_dir/ntfy.sh"
chown "$app:$app" "$install_dir/ntfy.sh"
chmod u+x "$install_dir/ntfy.sh"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# ADD ADMIN
#=================================================
ynh_script_progression "Adding admin user..."

# We have to wait until the server has created the
# Auth database after the first start. Only then we
# can create the admin user.
ynh_exec_as_app timeout 15s bash -c "until [ -f $install_dir/data/user.db ] ; do sleep 1; done"

ynh_exec_as_app NTFY_PASSWORD="$password" "$install_dir/ntfy" user -c "$install_dir/server.yml" add --role=admin "$admin"

#=================================================
# enable unifiedpush right to access read write
#=================================================
ynh_exec_as_app "$install_dir/ntfy.sh" access everyone "up*" rw

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation completed"
