#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Setting up source files..." --weight=6
ntfy_setup_source

ynh_script_progression --message="Adding configuration file..." --weight=1
ynh_add_config -t "server.yml" -d "$install_dir/server.yml"

ynh_script_progression --message="Configuring systemd service..." --weight=1
ynh_add_systemd_config

ynh_script_progression --message="Starting systemd service..." --weight=1
ynh_systemd_action --action=start

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app

ynh_script_progression --message="Adding a command wrapper..." --weight=1
ynh_add_config -t "ntfy.sh" -d "$install_dir/ntfy.sh"
chown $app:$app "$install_dir/ntfy.sh"
chmod u+x "$install_dir/ntfy.sh"

ynh_script_progression --message="Configuring web server..." --weight=2
ynh_add_nginx_config

ynh_script_progression --message="Adding admin user..." --weight=1
ynh_exec_as $app NTFY_PASSWORD="$password" $install_dir/ntfy.sh user add --role=admin $admin

ynh_script_progression --message="Installation completed" --last
