#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing service in YunoHost..." --weight=1
yunohost service remove $app

ynh_script_progression --message="Removing the systemd service..." --weight=1
ynh_remove_systemd_config

ynh_script_progression --message="Removing the web server configuration..." --weight=2
ynh_remove_nginx_config

ynh_script_progression --message="Removal completed" --last
