#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE

#=================================================
# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove "$app"
fi

ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_fail2ban

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal completed"
