#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

ynh_script_progression -m "Removing service in YunoHost..." -w 1
yunohost service remove $app

ynh_script_progression -m "Removing the systemd service..." -w 1
ynh_remove_systemd_config

ynh_script_progression -m "Removing the web server configuration..." -w 2
ynh_remove_nginx_config

ynh_script_progression -m "Removal completed" -l
