#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_script_progression -m "Restoring the main directory..." -w 1
ynh_restore_file -o "$install_dir"

ynh_script_progression -m "Restoring the web server configuration..." -w 1
ynh_restore_file -o "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_script_progression -m "Restoring the systemd configuration..." -w 1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_systemd_action -a enable

ynh_script_progression -m "Integrating service in YunoHost..." -w 1
yunohost service add $app

ynh_script_progression -m "Starting a systemd service..." -w 1
ynh_systemd_action -a start

ynh_script_progression -m "Reloading the web server..." -w 1
ynh_systemd_action --service-name=nginx --action restart

ynh_script_progression -m "Restoration completed" -l