#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set --key=protect_against_basic_auth_spoofing --value=false
yunohost app ssowatconf

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/data"

chmod -R 750 "$install_dir/data"
chown -R "$app:$app" "$install_dir"

ynh_safe_rm "$install_dir/client"
ynh_safe_rm "$install_dir/server"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Open Source Push Notification Server" --log="/var/log/$app/$app.log"

# Allow required basic auth
ynh_app_setting_set --key=auth-header --value=basic-with-password
ynh_app_setting_set --key=protect_against_basic_auth_spoofing --value=False

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="server.yml" --destination="$install_dir/server.yml"

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="limiting requests, excess:.* by zone.*client: <HOST>"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Updating simple command wrapper..."

ynh_config_add --template="ntfy.sh" --destination="$install_dir/ntfy.sh"

chown "$app:$app" "$install_dir/ntfy.sh"
chmod u+x "$install_dir/ntfy.sh"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
